# Generated by Django 4.2 on 2024-03-27 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('cashback', models.PositiveIntegerField(verbose_name='Сумма кешбэка')),
                ('cashback_status', models.BooleanField(default=False, verbose_name='Статус начислнения кешбэка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to='subscriptions.usersubscription', verbose_name='Подписка пользователя')),
            ],
        ),
    ]
